server:
    port: 8080

spring:
    application:
        name: kafka-sample
    kafka:
        bootstrap-servers: 124.223.93.211:9091,124.223.93.211:9092
        producer:
            retries: 3 # 默认Integer.MAX
            batch-size: 16384 # 默认16384，即16kb
            buffer-memory: 33554432 # 默认33554432，即32mb
            acks: 1 # 默认1，即leader确认收到便通知客户端成功
            compression-type: none # 默认none
            key-serializer: org.apache.kafka.common.serialization.StringSerializer # 没有默认值
            value-serializer: org.apache.kafka.common.serialization.StringSerializer # 没有默认值
            properties:
                retry:
                    backoff:
                        ms: 1000 # 默认100
                request:
                    timeout:
                        ms: 20000 # 默认30000
                delivery:
                    timeout:
                        ms: 60000 # 默认120000 (delivery = request * retry)
        consumer:
            group-id: ${spring.application.name}
            auto-offset-reset: earliest
            enable-auto-commit: false # 打开手动提交(1), 默认自动
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        listener:
            ack-mode: manual_immediate # 打开手动提交(2), 默认自动提交
        batch-consumer:
            consumer:
                bootstrap-servers: 124.223.93.211:9091,124.223.93.211:9092
                group-id: ${spring.application.name}
                auto-offset-reset: earliest
                enable-auto-commit: false
                max-poll-records: 10 # 批量消费最大数量
#                fetch-min-size: 10 # 一次消费最小字节
                key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
                value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            listener:
                type: batch # 批量消费
                concurrency: 1 # 为消费者指定线程数量，并发消费
                ack-mode: manual_immediate

logging:
    root: info
    pattern:
        console: "%-12(%d{yyyy-MM-dd HH:mm:ss.SSS}) |-%-5level [%thread] %c [%L] -| %msg%n"